"""Add start and stop script path columns to User and ReservedContainer

Adds nullable Text columns ``startScriptPath`` and ``stopScriptPath`` to both
the User table (profile-level defaults) and the ReservedContainer table
(per-reservation overrides). These store absolute paths to scripts inside the
container that run automatically on container start and stop.

Revision ID: 066815016cd8
Revises: a1b2c3d4e5f6
Create Date: 2026-04-01 19:14:30.624432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066815016cd8'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ReservedContainer', sa.Column('startScriptPath', sa.Text(), nullable=True))
    op.add_column('ReservedContainer', sa.Column('stopScriptPath', sa.Text(), nullable=True))
    op.add_column('User', sa.Column('startScriptPath', sa.Text(), nullable=True))
    op.add_column('User', sa.Column('stopScriptPath', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'stopScriptPath')
    op.drop_column('User', 'startScriptPath')
    op.drop_column('ReservedContainer', 'stopScriptPath')
    op.drop_column('ReservedContainer', 'startScriptPath')
    # ### end Alembic commands ###
