"""Add RoleMount table

Revision ID: 09ce4ba5c317
Revises: 4195f706b1ef
Create Date: 2025-07-14 19:14:33.838496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ce4ba5c317'
down_revision: Union[str, Sequence[str], None] = '4195f706b1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RoleMount',
    sa.Column('roleMountId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.Column('computerId', sa.Integer(), nullable=False),
    sa.Column('hostPath', sa.Text(), nullable=False),
    sa.Column('containerPath', sa.Text(), nullable=False),
    sa.Column('readOnly', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['computerId'], ['Computer.computerId'], ),
    sa.ForeignKeyConstraint(['roleId'], ['Role.roleId'], ),
    sa.PrimaryKeyConstraint('roleMountId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RoleMount')
    # ### end Alembic commands ###
