"""Add RoleMount table.

Create the RoleMount table to support role-based volume mount configurations
for containers. Each row maps a Role and Computer to a host-to-container path
binding with an optional read-only flag, allowing admins to define which
directories are mounted into containers for users of a given role on a
specific server.

Columns: roleMountId (PK), roleId (FK -> Role), computerId (FK -> Computer),
hostPath, containerPath, readOnly, createdAt, updatedAt.

Revision ID: 09ce4ba5c317
Revises: 4195f706b1ef
Create Date: 2025-07-14 19:14:33.838496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ce4ba5c317'
down_revision: Union[str, Sequence[str], None] = '4195f706b1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the RoleMount table with foreign keys to Role and Computer."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RoleMount',
    sa.Column('roleMountId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.Column('computerId', sa.Integer(), nullable=False),
    sa.Column('hostPath', sa.Text(), nullable=False),
    sa.Column('containerPath', sa.Text(), nullable=False),
    sa.Column('readOnly', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['computerId'], ['Computer.computerId'], ),
    sa.ForeignKeyConstraint(['roleId'], ['Role.roleId'], ),
    sa.PrimaryKeyConstraint('roleMountId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the RoleMount table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RoleMount')
    # ### end Alembic commands ###
