"""Add server monitoring tables

Revision ID: 0fc59e6770fa
Revises: ef6fec3e2f60
Create Date: 2025-07-19 18:13:55.112376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc59e6770fa'
down_revision: Union[str, Sequence[str], None] = 'ef6fec3e2f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ServerLogs',
    sa.Column('serverLogId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('computerId', sa.Integer(), nullable=False),
    sa.Column('logType', sa.Text(), nullable=False),
    sa.Column('logContent', sa.Text(), nullable=True),
    sa.Column('logLines', sa.Integer(), nullable=True),
    sa.Column('lastUpdatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['computerId'], ['Computer.computerId'], ),
    sa.PrimaryKeyConstraint('serverLogId'),
    sa.UniqueConstraint('computerId', 'logType', name='unique_computer_logtype')
    )
    op.create_table('ServerStatus',
    sa.Column('computerId', sa.Integer(), nullable=False),
    sa.Column('isOnline', sa.Boolean(), nullable=False),
    sa.Column('cpuUsagePercent', sa.Float(), nullable=True),
    sa.Column('cpuCores', sa.Integer(), nullable=True),
    sa.Column('memoryTotalBytes', sa.BigInteger(), nullable=True),
    sa.Column('memoryUsedBytes', sa.BigInteger(), nullable=True),
    sa.Column('memoryUsagePercent', sa.Float(), nullable=True),
    sa.Column('diskTotalBytes', sa.BigInteger(), nullable=True),
    sa.Column('diskUsedBytes', sa.BigInteger(), nullable=True),
    sa.Column('diskFreeBytes', sa.BigInteger(), nullable=True),
    sa.Column('diskUsagePercent', sa.Float(), nullable=True),
    sa.Column('dockerContainersRunning', sa.Integer(), nullable=True),
    sa.Column('dockerContainersTotal', sa.Integer(), nullable=True),
    sa.Column('loadAvg1Min', sa.Float(), nullable=True),
    sa.Column('loadAvg5Min', sa.Float(), nullable=True),
    sa.Column('loadAvg15Min', sa.Float(), nullable=True),
    sa.Column('systemUptimeSeconds', sa.BigInteger(), nullable=True),
    sa.Column('lastUpdatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['computerId'], ['Computer.computerId'], ),
    sa.PrimaryKeyConstraint('computerId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ServerStatus')
    op.drop_table('ServerLogs')
    # ### end Alembic commands ###
