"""Add lastBuiltAt to Container

Revision ID: 0fdcf8e1397f
Revises: 7f7ce5d92613
Create Date: 2026-04-01 07:10:13.296431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fdcf8e1397f'
down_revision: Union[str, Sequence[str], None] = '7f7ce5d92613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Container', sa.Column('lastBuiltAt', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Container', 'lastBuiltAt')
    # ### end Alembic commands ###
