"""Add managedExternally to Container

Revision ID: 17d0053185aa
Revises: 85e9cdef55ed
Create Date: 2026-04-01 05:23:26.068918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d0053185aa'
down_revision: Union[str, Sequence[str], None] = '85e9cdef55ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Container', sa.Column('managedExternally', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Container', 'managedExternally')
    # ### end Alembic commands ###
