"""Initial migration - current schema.

Baseline migration that captures the existing database schema at the time
Alembic was introduced. This revision contains no operations because the
tables already existed in the database; it serves as the starting point
for all subsequent migrations.

Revision ID: 4195f706b1ef
Revises:
Create Date: 2025-07-14 18:45:24.090125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4195f706b1ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """No-op: existing schema is already in place."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """No-op: baseline migration has nothing to revert."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
