"""Adds lastSeenAt column to User for tracking active session presence via frontend heartbeat.

Revision ID: 41b9cb8365c4
Revises: aed2d723523f
Create Date: 2026-05-29 12:58:32.641700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b9cb8365c4'
down_revision: Union[str, Sequence[str], None] = 'aed2d723523f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('lastSeenAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'lastSeenAt')
    # ### end Alembic commands ###
