"""Add unique constraint on ReservedContainerPort

Revision ID: 46f24bea56fc
Revises: 8040e9cd3d37
Create Date: 2026-04-03 03:24:41.289500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f24bea56fc'
down_revision: Union[str, Sequence[str], None] = '8040e9cd3d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_reserved_container_outside_port', 'ReservedContainerPort', ['reservedContainerId', 'outsidePort'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reserved_container_outside_port', 'ReservedContainerPort', type_='unique')
    # ### end Alembic commands ###
