"""Add imageSize to Container

Revision ID: 7f7ce5d92613
Revises: 17d0053185aa
Create Date: 2026-04-01 06:41:30.915877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f7ce5d92613'
down_revision: Union[str, Sequence[str], None] = '17d0053185aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Container', sa.Column('imageSize', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Container', 'imageSize')
    # ### end Alembic commands ###
