"""Add AuditLog table

Revision ID: 8040e9cd3d37
Revises: 80f5f80ca7b9
Create Date: 2026-04-02 19:17:57.229557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8040e9cd3d37'
down_revision: Union[str, Sequence[str], None] = '80f5f80ca7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuditLog',
    sa.Column('auditLogId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resourceType', sa.Text(), nullable=True),
    sa.Column('resourceId', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ipAddress', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.userId'], ),
    sa.PrimaryKeyConstraint('auditLogId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AuditLog')
    # ### end Alembic commands ###
