"""Add containerUsername, passwordCommand, sshKeyDeployCommands, containerCmd to Container

Revision ID: 85e9cdef55ed
Revises: aaed409fc5b4
Create Date: 2026-04-01 03:51:20.535455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e9cdef55ed'
down_revision: Union[str, Sequence[str], None] = 'aaed409fc5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Container', sa.Column('containerUsername', sa.Text(), nullable=True))
    op.add_column('Container', sa.Column('passwordCommand', sa.Text(), nullable=True))
    op.add_column('Container', sa.Column('sshKeyDeployCommands', sa.Text(), nullable=True))
    op.add_column('Container', sa.Column('containerCmd', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Container', 'containerCmd')
    op.drop_column('Container', 'sshKeyDeployCommands')
    op.drop_column('Container', 'passwordCommand')
    op.drop_column('Container', 'containerUsername')
    # ### end Alembic commands ###
