"""Add UserBlacklist and SystemSetting tables for admin configuration

Revision ID: 88881f85d96e
Revises: 0fc59e6770fa
Create Date: 2025-07-20 06:17:06.172860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88881f85d96e'
down_revision: Union[str, Sequence[str], None] = '0fc59e6770fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SystemSetting',
    sa.Column('systemSettingId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('settingKey', sa.Text(), nullable=False),
    sa.Column('settingValue', sa.Text(), nullable=True),
    sa.Column('dataType', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('systemSettingId'),
    sa.UniqueConstraint('settingKey')
    )
    op.create_table('UserBlacklist',
    sa.Column('userBlacklistId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('userBlacklistId'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserBlacklist')
    op.drop_table('SystemSetting')
    # ### end Alembic commands ###
