"""Add dockerfile builder columns to Container

Revision ID: aaed409fc5b4
Revises: 79bfcb9421cd
Create Date: 2026-03-31 19:15:32.308636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aaed409fc5b4'
down_revision: Union[str, Sequence[str], None] = '79bfcb9421cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Container', sa.Column('dockerfileCommands', sa.Text(), nullable=True))
    op.add_column('Container', sa.Column('baseImage', sa.Text(), nullable=True))
    op.add_column('Container', sa.Column('buildStatus', sa.Text(), nullable=True))
    op.add_column('Container', sa.Column('buildLog', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Container', 'buildLog')
    op.drop_column('Container', 'buildStatus')
    op.drop_column('Container', 'baseImage')
    op.drop_column('Container', 'dockerfileCommands')
    # ### end Alembic commands ###
