"""Add new columns shmSizePercent and ramDiskSizePercent to ReservedContainer

Revision ID: c0de8fe27417
Revises: 59c6691c5a04
Create Date: 2025-07-30 14:05:07.158593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0de8fe27417'
down_revision: Union[str, Sequence[str], None] = '59c6691c5a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('ReservedContainer', sa.Column('shmSizePercent', sa.Integer(), nullable=True))
    op.add_column('ReservedContainer', sa.Column('ramDiskSizePercent', sa.Integer(), nullable=True))
    
    # Update existing rows with default values
    op.execute("UPDATE ReservedContainer SET shmSizePercent = 50 WHERE shmSizePercent IS NULL")
    op.execute("UPDATE ReservedContainer SET ramDiskSizePercent = 0 WHERE ramDiskSizePercent IS NULL")
    
    # Make columns non-nullable (MySQL requires the full column type in ALTER)
    op.alter_column('ReservedContainer', 'shmSizePercent', 
                    existing_type=sa.Integer(),
                    nullable=False)
    op.alter_column('ReservedContainer', 'ramDiskSizePercent', 
                    existing_type=sa.Integer(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ReservedContainer', 'ramDiskSizePercent')
    op.drop_column('ReservedContainer', 'shmSizePercent')
    # ### end Alembic commands ###
