"""Add software version fields to ServerStatus.

Extend the ServerStatus table with ``softwareVersion`` (text) and
``versionUpdatedAt`` (datetime) columns so that each container server can
report which version of the platform software it is running and when that
version was last updated. Both columns are nullable to remain compatible
with servers that have not yet started reporting version data.

Revision ID: c434ddc20adc
Revises: fc130dbfe486
Create Date: 2025-07-21 15:30:05.814078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c434ddc20adc'
down_revision: Union[str, Sequence[str], None] = 'fc130dbfe486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add softwareVersion and versionUpdatedAt columns to ServerStatus."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ServerStatus', sa.Column('softwareVersion', sa.Text(), nullable=True))
    op.add_column('ServerStatus', sa.Column('versionUpdatedAt', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the versionUpdatedAt and softwareVersion columns from ServerStatus."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ServerStatus', 'versionUpdatedAt')
    op.drop_column('ServerStatus', 'softwareVersion')
    # ### end Alembic commands ###
