"""Add description field to Reservation table.

Add an optional text column ``description`` to the Reservation table so that
users can attach a free-form note explaining the purpose of their reservation
(e.g. project name, experiment details). The column is nullable and has no
default value.

Revision ID: ef6fec3e2f60
Revises: 09ce4ba5c317
Create Date: 2025-07-18 17:55:49.074232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6fec3e2f60'
down_revision: Union[str, Sequence[str], None] = '09ce4ba5c317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the nullable ``description`` text column to the Reservation table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reservation', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the ``description`` column from the Reservation table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Reservation', 'description')
    # ### end Alembic commands ###
