"""Add description field to Reservation table

Revision ID: ef6fec3e2f60
Revises: 09ce4ba5c317
Create Date: 2025-07-18 17:55:49.074232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6fec3e2f60'
down_revision: Union[str, Sequence[str], None] = '09ce4ba5c317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reservation', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Reservation', 'description')
    # ### end Alembic commands ###
