"""Remove unused UserStorage table

Revision ID: f3664bf56eff
Revises: c434ddc20adc
Create Date: 2025-07-24 02:44:19.647209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3664bf56eff'
down_revision: Union[str, Sequence[str], None] = 'c434ddc20adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint first
    op.drop_constraint('UserStorage_ibfk_1', 'UserStorage', type_='foreignkey')
    # Then drop the index
    op.drop_index(op.f('userId'), table_name='UserStorage')
    # Finally drop the table
    op.drop_table('UserStorage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserStorage',
    sa.Column('userStorageId', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('maxSpace', mysql.FLOAT(), nullable=False),
    sa.Column('maxSpaceFormat', mysql.TEXT(), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.userId'], name='UserStorage_ibfk_1'),
    sa.PrimaryKeyConstraint('userStorageId'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('userId'), 'UserStorage', ['userId'], unique=True)
    # ### end Alembic commands ###
