"""Change ServerLogs logContent from TEXT to LONGTEXT.

Alter the ``logContent`` column in the ServerLogs table from MySQL TEXT
(~64 KB limit) to LONGTEXT (~4 GB limit) to accommodate large log outputs
such as full Docker build logs or lengthy system journal exports that
exceeded the previous size constraint.

Revision ID: fc130dbfe486
Revises: 88881f85d96e
Create Date: 2025-07-20 07:25:50.156320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fc130dbfe486'
down_revision: Union[str, Sequence[str], None] = '88881f85d96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Alter ServerLogs.logContent column type from TEXT to LONGTEXT."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ServerLogs', 'logContent',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert ServerLogs.logContent column type from LONGTEXT back to TEXT."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ServerLogs', 'logContent',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
